--Airport
INSERT INTO airport (city, code) VALUES ('Aalborg','AAL');
INSERT INTO airport (city, code) VALUES ('Aalesund','AES');
INSERT INTO airport (city, code) VALUES ('Aarhus','AAR');
INSERT INTO airport (city, code) VALUES ('Abbotsford, BC','YXX');
INSERT INTO airport (city, code) VALUES ('Abbotsford, BC','YXX');
INSERT INTO airport (city, code) VALUES ('Aberdeen','ABZ');
INSERT INTO airport (city, code) VALUES ('Aberdeen, SD','ABR');
INSERT INTO airport (city, code) VALUES ('Abidjan','ABJ');
INSERT INTO airport (city, code) VALUES ('Abilene, TX','ABI');
INSERT INTO airport (city, code) VALUES ('Abu Dhabi','AUH');
INSERT INTO airport (city, code) VALUES ('Abuja','ABV');
INSERT INTO airport (city, code) VALUES ('Acapulco','ACA');
INSERT INTO airport (city, code) VALUES ('Accra','ACC');
INSERT INTO airport (city, code) VALUES ('Adana','ADA');
INSERT INTO airport (city, code) VALUES ('Addis Ababa','ADD');
INSERT INTO airport (city, code) VALUES ('Adelaide, S.A.','ADL');
INSERT INTO airport (city, code) VALUES ('Aden','ADE');
INSERT INTO airport (city, code) VALUES ('Adiyaman','ADF');
INSERT INTO airport (city, code) VALUES ('Agadir','AGA');
INSERT INTO airport (city, code) VALUES ('Agana','GUM');
INSERT INTO airport (city, code) VALUES ('Aguadilla','BQN');
INSERT INTO airport (city, code) VALUES ('Aguascalientes','AGU');
INSERT INTO airport (city, code) VALUES ('Ahe','AHE');
INSERT INTO airport (city, code) VALUES ('Ahmedabad','AMD');
INSERT INTO airport (city, code) VALUES ('Ajaccio, Corsica','AJA');
INSERT INTO airport (city, code) VALUES ('Akita','AXT');
INSERT INTO airport (city, code) VALUES ('Akron, OH','CAK');
INSERT INTO airport (city, code) VALUES ('Alamosa, CO','ALS');
INSERT INTO airport (city, code) VALUES ('Albany, GA','ABY');
INSERT INTO airport (city, code) VALUES ('Albany, NY','ALB');
INSERT INTO airport (city, code) VALUES ('Albenga','ALL');
INSERT INTO airport (city, code) VALUES ('Albuquerque, NM','ABQ');
INSERT INTO airport (city, code) VALUES ('Albury, N.S.W.','ABX');
INSERT INTO airport (city, code) VALUES ('Alexandria','ALY');
INSERT INTO airport (city, code) VALUES ('Alexandria','HBE');
INSERT INTO airport (city, code) VALUES ('Alexandria, LA','AEX');
INSERT INTO airport (city, code) VALUES ('Alexandroupolis','AXD');
INSERT INTO airport (city, code) VALUES ('Alghero, Sardinia','AHO');
INSERT INTO airport (city, code) VALUES ('Algiers','ALG');
INSERT INTO airport (city, code) VALUES ('Alicante','ALC');
INSERT INTO airport (city, code) VALUES ('Alice Springs, N.T.','ASP');
INSERT INTO airport (city, code) VALUES ('Alice Town, North Bimini Island','NSB');
INSERT INTO airport (city, code) VALUES ('Allentown, PA','ABE');
INSERT INTO airport (city, code) VALUES ('Alliance, NE','AIA');
INSERT INTO airport (city, code) VALUES ('Almaty','ALA');
INSERT INTO airport (city, code) VALUES ('Almeria','LEI');
INSERT INTO airport (city, code) VALUES ('Alor Setar','AOR');
INSERT INTO airport (city, code) VALUES ('Alpena, MI','APN');
INSERT INTO airport (city, code) VALUES ('Alta','ALF');
INSERT INTO airport (city, code) VALUES ('Altenrhein','ACH');
INSERT INTO airport (city, code) VALUES ('Altoona, PA','AOO');
INSERT INTO airport (city, code) VALUES ('Amarillo, TX','AMA');
INSERT INTO airport (city, code) VALUES ('Amman','AMM');
INSERT INTO airport (city, code) VALUES ('Amsterdam','AMS');
INSERT INTO airport (city, code) VALUES ('Anahim Lake, BC','YAA');
INSERT INTO airport (city, code) VALUES ('Anahim Lake, BC','YAA');
INSERT INTO airport (city, code) VALUES ('Anchorage, AK','ANC');
INSERT INTO airport (city, code) VALUES ('Ancona','AOI');
INSERT INTO airport (city, code) VALUES ('Andros Town','ASD');
INSERT INTO airport (city, code) VALUES ('Angeles City','CRK');
INSERT INTO airport (city, code) VALUES ('Angra do Heroismo, Terceira Island','TER');
INSERT INTO airport (city, code) VALUES ('Ankara','ESB');
INSERT INTO airport (city, code) VALUES ('Annaba','AAE');
INSERT INTO airport (city, code) VALUES ('Annecy','NCY');
INSERT INTO airport (city, code) VALUES ('Antalya','AYT');
INSERT INTO airport (city, code) VALUES ('Antananarivo','TNR');
INSERT INTO airport (city, code) VALUES ('Antofagasta','ANF');
INSERT INTO airport (city, code) VALUES ('Antwerp','ANR');
INSERT INTO airport (city, code) VALUES ('Aomori','AOJ');
INSERT INTO airport (city, code) VALUES ('Aosta','AOT');
INSERT INTO airport (city, code) VALUES ('Appleton, WI','ATW');
INSERT INTO airport (city, code) VALUES ('Ardabil','ADU');
INSERT INTO airport (city, code) VALUES ('Arequipa','AQP');
INSERT INTO airport (city, code) VALUES ('Argostoli, Kefalonia Island','EFL');
INSERT INTO airport (city, code) VALUES ('Arica','ARI');
INSERT INTO airport (city, code) VALUES ('Arkhangelsk','ARH');
INSERT INTO airport (city, code) VALUES ('Armidale, N.S.W.','ARM');
INSERT INTO airport (city, code) VALUES ('Arrecife, Lanzarote Island','ACE');
INSERT INTO airport (city, code) VALUES ('Arusha','ARK');
INSERT INTO airport (city, code) VALUES ('Arviat, NWT','YEK');
INSERT INTO airport (city, code) VALUES ('Arviat, NWT','YEK');
INSERT INTO airport (city, code) VALUES ('Arvidsjaur','AJR');
INSERT INTO airport (city, code) VALUES ('Asheville, NC','AVL');
INSERT INTO airport (city, code) VALUES ('Asmara','ASM');
INSERT INTO airport (city, code) VALUES ('Aspen, CO','ASE');
INSERT INTO airport (city, code) VALUES ('Astana','TSE');
INSERT INTO airport (city, code) VALUES ('Asuncion','ASU');
INSERT INTO airport (city, code) VALUES ('Aswan','ASW');
INSERT INTO airport (city, code) VALUES ('Athens','ATH');
INSERT INTO airport (city, code) VALUES ('Athens, GA','AHN');
INSERT INTO airport (city, code) VALUES ('Atlanta, GA','ATL');
INSERT INTO airport (city, code) VALUES ('Atlantic City, NJ','ACY');
INSERT INTO airport (city, code) VALUES ('Auckland','AKL');
INSERT INTO airport (city, code) VALUES ('Augusta, GA','AGS');
INSERT INTO airport (city, code) VALUES ('Augusta, ME','AUG');
INSERT INTO airport (city, code) VALUES ('Austin, TX','AUS');
INSERT INTO airport (city, code) VALUES ('Avarua, Rarotonga Island','RAR');
INSERT INTO airport (city, code) VALUES ('Ayers Rock, N.T.','AYQ');
INSERT INTO airport (city, code) VALUES ('Bacolod','BCD');
INSERT INTO airport (city, code) VALUES ('Badajoz','BJZ');
INSERT INTO airport (city, code) VALUES ('Baghdad','SDA');
INSERT INTO airport (city, code) VALUES ('Bagotville, PQ','YBG');
INSERT INTO airport (city, code) VALUES ('Bagotville, PQ','YBG');
INSERT INTO airport (city, code) VALUES ('Baie-Comeau, PQ','YBC');
INSERT INTO airport (city, code) VALUES ('Baie-Comeau, PQ','YBC');
INSERT INTO airport (city, code) VALUES ('Bakersfield, CA','BFL');
INSERT INTO airport (city, code) VALUES ('Baku','BAK');
INSERT INTO airport (city, code) VALUES ('Baku','GYD');
INSERT INTO airport (city, code) VALUES ('Balaton','SOB');
INSERT INTO airport (city, code) VALUES ('Balephuil','TRE');
INSERT INTO airport (city, code) VALUES ('Balikpapan, Kalimantan','BPN');
INSERT INTO airport (city, code) VALUES ('Ballina, N.S.W.','BNK');
INSERT INTO airport (city, code) VALUES ('Balmaceda','BBA');
INSERT INTO airport (city, code) VALUES ('Baltimore, MD','BWI');
INSERT INTO airport (city, code) VALUES ('Ban Me Thuot','BMV');
INSERT INTO airport (city, code) VALUES ('Bandar Seri Begawan','BWN');
INSERT INTO airport (city, code) VALUES ('Bangalore','BLR');
INSERT INTO airport (city, code) VALUES ('Bangda','BPX');
INSERT INTO airport (city, code) VALUES ('Bangkok','BKK');
INSERT INTO airport (city, code) VALUES ('Bangor, ME','BGR');
INSERT INTO airport (city, code) VALUES ('Bangui','BGF');
INSERT INTO airport (city, code) VALUES ('Banjul','BJL');
INSERT INTO airport (city, code) VALUES ('Bar Harbor, ME','BHB');
INSERT INTO airport (city, code) VALUES ('Barcelona','BCN');
INSERT INTO airport (city, code) VALUES ('Bardufoss','BDU');
INSERT INTO airport (city, code) VALUES ('Bari','BRI');
INSERT INTO airport (city, code) VALUES ('Barisal','BZL');
INSERT INTO airport (city, code) VALUES ('Barranquilla','BAQ');
INSERT INTO airport (city, code) VALUES ('Barrow, AK','BRW');
INSERT INTO airport (city, code) VALUES ('Basel','BSL');
INSERT INTO airport (city, code) VALUES ('Basseterre','SKB');
INSERT INTO airport (city, code) VALUES ('Bastia, Corsica','BIA');
INSERT INTO airport (city, code) VALUES ('Bathurst, N.S.W.','BHS');
INSERT INTO airport (city, code) VALUES ('Baton Rouge, LA','BTR');
INSERT INTO airport (city, code) VALUES ('Bauru','BAU');
INSERT INTO airport (city, code) VALUES ('Beaumont, TX','BPT');
INSERT INTO airport (city, code) VALUES ('Beauvais','BVA');
INSERT INTO airport (city, code) VALUES ('Beckley, WV','BKW');
INSERT INTO airport (city, code) VALUES ('Bedford, MA','BED');
INSERT INTO airport (city, code) VALUES ('Beef Island, Tortola','EIS');
INSERT INTO airport (city, code) VALUES ('Beijing','BJS');
INSERT INTO airport (city, code) VALUES ('Beirut','BEY');
INSERT INTO airport (city, code) VALUES ('Belem','BEL');
INSERT INTO airport (city, code) VALUES ('Belfast','BFS');
INSERT INTO airport (city, code) VALUES ('Belfast','BHD');
INSERT INTO airport (city, code) VALUES ('Belgrade','BEG');
INSERT INTO airport (city, code) VALUES ('Belize City','BZE');
INSERT INTO airport (city, code) VALUES ('Bellingham, WA','BLI');
INSERT INTO airport (city, code) VALUES ('Belo Horizonte','CNF');
INSERT INTO airport (city, code) VALUES ('Bemidji, MN','BJI');
INSERT INTO airport (city, code) VALUES ('Benbecula','BEB');
INSERT INTO airport (city, code) VALUES ('Benguela','BUG');
INSERT INTO airport (city, code) VALUES ('Bergen','BGO');
INSERT INTO airport (city, code) VALUES ('Berlin','BER - All Airports');
INSERT INTO airport (city, code) VALUES ('Berlin','SXF');
INSERT INTO airport (city, code) VALUES ('Berlin','THF');
INSERT INTO airport (city, code) VALUES ('Berlin','TXL');
INSERT INTO airport (city, code) VALUES ('Berne','BRN');
INSERT INTO airport (city, code) VALUES ('Bethel, AK','BET');
INSERT INTO airport (city, code) VALUES ('Bettles, AK','BTT');
INSERT INTO airport (city, code) VALUES ('Biak, Papua','BIK');
INSERT INTO airport (city, code) VALUES ('Biarritz','BIQ');
INSERT INTO airport (city, code) VALUES ('Bilbao','BIO');
INSERT INTO airport (city, code) VALUES ('Billings, MT','BIL');
INSERT INTO airport (city, code) VALUES ('Billund','BLL');
INSERT INTO airport (city, code) VALUES ('Binghamton, NY','BGM');
INSERT INTO airport (city, code) VALUES ('Bintulu, Sarawak','BTU');
INSERT INTO airport (city, code) VALUES ('Birmingham','BHX');
INSERT INTO airport (city, code) VALUES ('Birmingham, AL','BHM');
INSERT INTO airport (city, code) VALUES ('Bishkek','FRU');
INSERT INTO airport (city, code) VALUES ('Bismarck, ND','BIS');
INSERT INTO airport (city, code) VALUES ('Bissau','OXB');
INSERT INTO airport (city, code) VALUES ('Blantyre','BLZ');
INSERT INTO airport (city, code) VALUES ('Blenheim','BHE');
INSERT INTO airport (city, code) VALUES ('Bloemfontein','BFN');
INSERT INTO airport (city, code) VALUES ('Bloomington, IL','BMI');
INSERT INTO airport (city, code) VALUES ('Bloomington, IN','BMG');
INSERT INTO airport (city, code) VALUES ('Bluefield, WV','BLF');
INSERT INTO airport (city, code) VALUES ('Bodo','BOO');
INSERT INTO airport (city, code) VALUES ('Bogota','BOG');
INSERT INTO airport (city, code) VALUES ('Boise, ID','BOI');
INSERT INTO airport (city, code) VALUES ('Bologna','BLQ');
INSERT INTO airport (city, code) VALUES ('Bolzano','BZO');
INSERT INTO airport (city, code) VALUES ('Bordeaux','BOD');
INSERT INTO airport (city, code) VALUES ('Borlange','BLE');
INSERT INTO airport (city, code) VALUES ('Boston, MA','BOS');
INSERT INTO airport (city, code) VALUES ('Bozeman, MT','BZN');
INSERT INTO airport (city, code) VALUES ('Brasilia','BSB');
INSERT INTO airport (city, code) VALUES ('Bratislava','BTS');
INSERT INTO airport (city, code) VALUES ('Brazzaville','BZV');
INSERT INTO airport (city, code) VALUES ('Bremen','BRE');
INSERT INTO airport (city, code) VALUES ('Brest','BES');
INSERT INTO airport (city, code) VALUES ('Bridgetown','BGI');
INSERT INTO airport (city, code) VALUES ('Brindisi','BDS');
INSERT INTO airport (city, code) VALUES ('Brisbane, Qld.','BNE');
INSERT INTO airport (city, code) VALUES ('Bristol','BRS');
INSERT INTO airport (city, code) VALUES ('Broken Hill, N.S.W.','BHQ');
INSERT INTO airport (city, code) VALUES ('Brookings, SD','BKX');
INSERT INTO airport (city, code) VALUES ('Broome, W.A.','BME');
INSERT INTO airport (city, code) VALUES ('Brownsville, TX','BRO');
INSERT INTO airport (city, code) VALUES ('Brunswick, GA','BQK');
INSERT INTO airport (city, code) VALUES ('Brussels','BRU');
INSERT INTO airport (city, code) VALUES ('Bucharest','OTP');
INSERT INTO airport (city, code) VALUES ('Budapest','BUD');
INSERT INTO airport (city, code) VALUES ('Buenos Aires','EZE');
INSERT INTO airport (city, code) VALUES ('Buffalo, NY','BUF');
INSERT INTO airport (city, code) VALUES ('Bujumbura','BJM');
INSERT INTO airport (city, code) VALUES ('Bulawayo','BUQ');
INSERT INTO airport (city, code) VALUES ('Bundaberg, Qld.','BDB');
INSERT INTO airport (city, code) VALUES ('Burbank, CA','BUR');
INSERT INTO airport (city, code) VALUES ('Buri Ram','BFV');
INSERT INTO airport (city, code) VALUES ('Burlington, IA','BRL');
INSERT INTO airport (city, code) VALUES ('Burlington, MA','BBF');
INSERT INTO airport (city, code) VALUES ('Burlington, VT','BTV');
INSERT INTO airport (city, code) VALUES ('Busan, Korea','PUS');
INSERT INTO airport (city, code) VALUES ('Butte, MT','BTM');
INSERT INTO airport (city, code) VALUES ('Butuan','BXU');
INSERT INTO airport (city, code) VALUES ('Bydgoszcz','BZG');
INSERT INTO airport (city, code) VALUES ('Caen','CFR');
INSERT INTO airport (city, code) VALUES ('Cagayan de Oro','CGY');
INSERT INTO airport (city, code) VALUES ('Cagliari, Sardinia','CAG');
INSERT INTO airport (city, code) VALUES ('Cairns, Qld.','CNS');
INSERT INTO airport (city, code) VALUES ('Cairo','CAI');
INSERT INTO airport (city, code) VALUES ('Calcutta','CCU');
INSERT INTO airport (city, code) VALUES ('Calgary, AB','YYC');
INSERT INTO airport (city, code) VALUES ('Calgary, AB','YYC');
INSERT INTO airport (city, code) VALUES ('Cali','CLO');
INSERT INTO airport (city, code) VALUES ('Calvi, Corsica','CLY');
INSERT INTO airport (city, code) VALUES ('Campbell River, BC','YBL');
INSERT INTO airport (city, code) VALUES ('Campbell River, BC','YBL');
INSERT INTO airport (city, code) VALUES ('Campbeltown','CAL');
INSERT INTO airport (city, code) VALUES ('Campeche','CPE');
INSERT INTO airport (city, code) VALUES ('Canberra, A.C.T.','CBR');
INSERT INTO airport (city, code) VALUES ('Cancun','CUN');
INSERT INTO airport (city, code) VALUES ('Cap-aux-Meules, Magdalens Islands, PQ','YGR');
INSERT INTO airport (city, code) VALUES ('Cap-aux-Meules,','YGR');
INSERT INTO airport (city, code) VALUES ('Cape Girardeau, MO','CGI');
INSERT INTO airport (city, code) VALUES ('Cape Town','CPT');
INSERT INTO airport (city, code) VALUES ('Caracas','CCS');
INSERT INTO airport (city, code) VALUES ('Cardiff','CWL');
INSERT INTO airport (city, code) VALUES ('Carlsbad, CA','CLD');
INSERT INTO airport (city, code) VALUES ('Carlsbad, NM','CNM');
INSERT INTO airport (city, code) VALUES ('Cartagena','CTG');
INSERT INTO airport (city, code) VALUES ('Casablanca','CMN');
INSERT INTO airport (city, code) VALUES ('Casper, WY','CPR');
INSERT INTO airport (city, code) VALUES ('Castlegar, BC','YCG');
INSERT INTO airport (city, code) VALUES ('Castlegar, BC','YCG');
INSERT INTO airport (city, code) VALUES ('Castries','SLU');
INSERT INTO airport (city, code) VALUES ('Catania, Sicily','CTA');
INSERT INTO airport (city, code) VALUES ('Cayenne','CAY');
INSERT INTO airport (city, code) VALUES ('Cayman Brac','CYB');
INSERT INTO airport (city, code) VALUES ('Cebu','CEB');
INSERT INTO airport (city, code) VALUES ('Cedar Rapids, IA','CID');
INSERT INTO airport (city, code) VALUES ('Ceduna, S.A.','CED');
INSERT INTO airport (city, code) VALUES ('Champaign, IL','CMI');
INSERT INTO airport (city, code) VALUES ('Changchun','CGQ');
INSERT INTO airport (city, code) VALUES ('Changsha','CSX');
INSERT INTO airport (city, code) VALUES ('Chania, Crete','CHQ');
INSERT INTO airport (city, code) VALUES ('Charleston, SC','CHS');
INSERT INTO airport (city, code) VALUES ('Charleston, WV','CRW');
INSERT INTO airport (city, code) VALUES ('Charleville, Qld.','CTL');
INSERT INTO airport (city, code) VALUES ('Charlotte Amalie, St. Thomas','STT');
INSERT INTO airport (city, code) VALUES ('Charlotte, NC','CLT');
INSERT INTO airport (city, code) VALUES ('Charlottesville, VA','CHO');
INSERT INTO airport (city, code) VALUES ('Charlottetown, PEI','YYG');
INSERT INTO airport (city, code) VALUES ('Charlottetown, PEI','YYG');
INSERT INTO airport (city, code) VALUES ('Chattanooga, TN','CHA');
INSERT INTO airport (city, code) VALUES ('Chengdu','CTU');
INSERT INTO airport (city, code) VALUES ('Chennai (Madras)','MAA');
INSERT INTO airport (city, code) VALUES ('Chetumal','CTM');
INSERT INTO airport (city, code) VALUES ('Cheyenne, WY','CYS');
INSERT INTO airport (city, code) VALUES ('Chiang Mai','CNX');
INSERT INTO airport (city, code) VALUES ('Chiang Rai','CEI');
INSERT INTO airport (city, code) VALUES ('Chibougamau, PQ','YMT');
INSERT INTO airport (city, code) VALUES ('Chibougamau, PQ','YMT');
INSERT INTO airport (city, code) VALUES ('Chicago, IL','CHI - All');
INSERT INTO airport (city, code) VALUES ('Chicago, IL','MDW');
INSERT INTO airport (city, code) VALUES ('Chicago, IL','ORD');
INSERT INTO airport (city, code) VALUES ('Chico, CA','CIC');
INSERT INTO airport (city, code) VALUES ('Chihuahua','CUU');
INSERT INTO airport (city, code) VALUES ('Chios','JKH');
INSERT INTO airport (city, code) VALUES ('Chisinau','KIV');
INSERT INTO airport (city, code) VALUES ('Chongqing','CKG');
INSERT INTO airport (city, code) VALUES ('Christchurch','CHC');
INSERT INTO airport (city, code) VALUES ('Christiansted, St. Croix','STX');
INSERT INTO airport (city, code) VALUES ('Churchill, MB','YYQ');
INSERT INTO airport (city, code) VALUES ('Churchill, MB','YYQ');
INSERT INTO airport (city, code) VALUES ('Cincinnati, OH','CVG');
INSERT INTO airport (city, code) VALUES ('Ciudad Bolivar','CBL');
INSERT INTO airport (city, code) VALUES ('Ciudad Del Carmen','CME');
INSERT INTO airport (city, code) VALUES ('Ciudad del Este','AGT');
INSERT INTO airport (city, code) VALUES ('Ciudad Juarez','CJS');
INSERT INTO airport (city, code) VALUES ('Ciudad Obregon','CEN');
INSERT INTO airport (city, code) VALUES ('Ciudad Victoria','CVM');
INSERT INTO airport (city, code) VALUES ('Clarksburg, WV','CKB');
INSERT INTO airport (city, code) VALUES ('Clermont-Ferrand','CFE');
INSERT INTO airport (city, code) VALUES ('Cleveland, OH','CLE');
INSERT INTO airport (city, code) VALUES ('Clovis, NM','CVN');
INSERT INTO airport (city, code) VALUES ('Cockburn Town, San Salvador Island','ZSA');
INSERT INTO airport (city, code) VALUES ('Cody, WY','COD');
INSERT INTO airport (city, code) VALUES ('Coffs Harbour, N.S.W.','CFS');
INSERT INTO airport (city, code) VALUES ('Colima','CLQ');
INSERT INTO airport (city, code) VALUES ('College Station, TX','CLL');
INSERT INTO airport (city, code) VALUES ('Cologne','CGN');
INSERT INTO airport (city, code) VALUES ('Colombo','CMB');
INSERT INTO airport (city, code) VALUES ('Colorado Springs, CO','COS');
INSERT INTO airport (city, code) VALUES ('Columbia, MO','COU');
INSERT INTO airport (city, code) VALUES ('Columbia, SC','CAE');
INSERT INTO airport (city, code) VALUES ('Columbus, GA','CSG');
INSERT INTO airport (city, code) VALUES ('Columbus, IN','CLU');
INSERT INTO airport (city, code) VALUES ('Columbus, MS','GTR');
INSERT INTO airport (city, code) VALUES ('Columbus, NE','OLU');
INSERT INTO airport (city, code) VALUES ('Columbus, OH','CMH');
INSERT INTO airport (city, code) VALUES ('Conakry','CKY');
INSERT INTO airport (city, code) VALUES ('Concepcion','CCP');
INSERT INTO airport (city, code) VALUES ('Connaught','NOC');
INSERT INTO airport (city, code) VALUES ('Coober Pedy, S.A.','CPD');
INSERT INTO airport (city, code) VALUES ('Copenhagen','CPH');
INSERT INTO airport (city, code) VALUES ('Copiapo','CPO');
INSERT INTO airport (city, code) VALUES ('Cordoba','COR');
INSERT INTO airport (city, code) VALUES ('Cordova, AK','CDV');
INSERT INTO airport (city, code) VALUES ('Cork','ORK');
INSERT INTO airport (city, code) VALUES ('Corpus Christi, TX','CRP');
INSERT INTO airport (city, code) VALUES ('Cotabato','CBO');
INSERT INTO airport (city, code) VALUES ('Cozumel','CZM');
INSERT INTO airport (city, code) VALUES ('Cranbrook, BC','YXC');
INSERT INTO airport (city, code) VALUES ('Cranbrook, BC','YXC');
INSERT INTO airport (city, code) VALUES ('Crotone','CRV');
INSERT INTO airport (city, code) VALUES ('Cubi Point Nas','NCP');
INSERT INTO airport (city, code) VALUES ('Culiacan','CUL');
INSERT INTO airport (city, code) VALUES ('Curitiba','CWB');
INSERT INTO airport (city, code) VALUES ('Cusco','CUZ');
INSERT INTO airport (city, code) VALUES ('Da Nang','DAD');
INSERT INTO airport (city, code) VALUES ('Dakar','DKR');
INSERT INTO airport (city, code) VALUES ('Dalaman','DLM');
INSERT INTO airport (city, code) VALUES ('Dali City','DLU');
INSERT INTO airport (city, code) VALUES ('Dalian','DLC');
INSERT INTO airport (city, code) VALUES ('Dallas, TX','DAL');
INSERT INTO airport (city, code) VALUES ('Dallas, TX','DFW');
INSERT INTO airport (city, code) VALUES ('Damascus','DAM');
INSERT INTO airport (city, code) VALUES ('Dangriga','DGA');
INSERT INTO airport (city, code) VALUES ('Dar es Salaam','DAR');
INSERT INTO airport (city, code) VALUES ('Darwin, N.T.','DRW');
INSERT INTO airport (city, code) VALUES ('Davao','DVO');
INSERT INTO airport (city, code) VALUES ('Dawadmi','DWD');
INSERT INTO airport (city, code) VALUES ('Dayong','DYG');
INSERT INTO airport (city, code) VALUES ('Dayton, OH','DAY');
INSERT INTO airport (city, code) VALUES ('Daytona Beach, FL','DAB');
INSERT INTO airport (city, code) VALUES ('Deadmans Cay, Long Island','LGI');
INSERT INTO airport (city, code) VALUES ('Deboyne','DOY');
INSERT INTO airport (city, code) VALUES ('Decatur, IL','DEC');
INSERT INTO airport (city, code) VALUES ('Deer Lake, NF','YDF');
INSERT INTO airport (city, code) VALUES ('Deer Lake, NF','YDF');
INSERT INTO airport (city, code) VALUES ('Delhi','DEL');
INSERT INTO airport (city, code) VALUES ('Denpasar, Bali','DPS');
INSERT INTO airport (city, code) VALUES ('Denver, CO','DEN');
INSERT INTO airport (city, code) VALUES ('Des Moines, IA','DSM');
INSERT INTO airport (city, code) VALUES ('Detroit, MI','DTT - All');
INSERT INTO airport (city, code) VALUES ('Detroit, MI','DTW');
INSERT INTO airport (city, code) VALUES ('Devils Lake, ND','DVL');
INSERT INTO airport (city, code) VALUES ('Devonport, Tas.','DPO');
INSERT INTO airport (city, code) VALUES ('Dhahran','DHA');
INSERT INTO airport (city, code) VALUES ('Dhaka','DAC');
INSERT INTO airport (city, code) VALUES ('Dickinson, ND','DIK');
INSERT INTO airport (city, code) VALUES ('Dien-Bien-Phu','DIN');
INSERT INTO airport (city, code) VALUES ('Dillingham, AK','DLG');
INSERT INTO airport (city, code) VALUES ('Dipolog','DPL');
INSERT INTO airport (city, code) VALUES ('Djibouti','JIB');
INSERT INTO airport (city, code) VALUES ('Dnepropetrovsk','DNK');
INSERT INTO airport (city, code) VALUES ('Dodge City, KS','DDC');
INSERT INTO airport (city, code) VALUES ('Doha','DOH');
INSERT INTO airport (city, code) VALUES ('Doncaster','DSA');
INSERT INTO airport (city, code) VALUES ('Donetsk','DOK');
INSERT INTO airport (city, code) VALUES ('Dortmund','DTM');
INSERT INTO airport (city, code) VALUES ('Dothan, AL','DHN');
INSERT INTO airport (city, code) VALUES ('Douala','DLA');
INSERT INTO airport (city, code) VALUES ('Dresden','DRS');
INSERT INTO airport (city, code) VALUES ('Dryden, ON','YHD');
INSERT INTO airport (city, code) VALUES ('Dryden, ON','YHD');
INSERT INTO airport (city, code) VALUES ('Du Bois, PA','DUJ');
INSERT INTO airport (city, code) VALUES ('Dubai','DXB');
INSERT INTO airport (city, code) VALUES ('Dubbo, N.S.W.','DBO');
INSERT INTO airport (city, code) VALUES ('Dublin','DUB');
INSERT INTO airport (city, code) VALUES ('Dubrovnik','DBV');
INSERT INTO airport (city, code) VALUES ('Dubuque, IA','DBQ');
INSERT INTO airport (city, code) VALUES ('Duluth, MN','DLH');
INSERT INTO airport (city, code) VALUES ('Dumaguete','DGT');
INSERT INTO airport (city, code) VALUES ('Dunedin','DUD');
INSERT INTO airport (city, code) VALUES ('Durango','DGO');
INSERT INTO airport (city, code) VALUES ('Durango, CO','DRO');
INSERT INTO airport (city, code) VALUES ('Durban','DUR');
INSERT INTO airport (city, code) VALUES ('Dushanbe','DYU');
INSERT INTO airport (city, code) VALUES ('Dusseldorf','DUS');
INSERT INTO airport (city, code) VALUES ('Dutch Harbor, Un Island, AK','DUT');
INSERT INTO airport (city, code) VALUES ('East London','ELS');
INSERT INTO airport (city, code) VALUES ('East Midlands','EMA');
INSERT INTO airport (city, code) VALUES ('Eau Claire, WI','EAU');
INSERT INTO airport (city, code) VALUES ('Edinburgh','EDI');
INSERT INTO airport (city, code) VALUES ('Edmonton, AB','YEG');
INSERT INTO airport (city, code) VALUES ('Edmonton, AB','YEG');

--Transportation
INSERT INTO transportation (name) VALUES ('Rental Car');
INSERT INTO transportation (name) VALUES ('Private Driver');
INSERT INTO transportation (name) VALUES ('Taxi/Uber');
INSERT INTO transportation (name) VALUES ('Helicopter');
INSERT INTO transportation (name) VALUES ('Bike');
INSERT INTO transportation (name) VALUES ('Skateboard');
INSERT INTO transportation (name) VALUES ('Walking');
INSERT INTO transportation (name) VALUES ('Bus');
INSERT INTO transportation (name) VALUES ('Train/Metro');

